### ISSUE TITLE
Fonts not exported, even with 0.2.9.21

### ISSUE THREAD

**Issue by MarcusRiemer** [chcg/NPP_ExportPlugin#10]
I am aware that the latest release (https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.2.9.21) fixes some issues with the newest version of Notepad++. The release does help, but for whatever reason it does not export the font which means I keep ending up with non-monospaced code fragments in Powerpoint (which is my primary usecase).

**Comment by dfs-** [comment]
In Microsoft Office products you need to use the "insert options" to determine it to keep the original formatting instead of combining the styles. See the screenshot below - you need to use the second of three options.

![powerpoint_2016_insert_options](https://user-images.githubusercontent.com/6563013/66764112-70270580-eea9-11e9-9b76-23f8e5325af8.png)

**Comment by MarcusRiemer** [comment]
Yes, I am using that insert option. And I am 100% certain that it drove me up the wall two days ago because it "stopped working" after the Notepad++ update. But as I attempted to make a video showing the problem, everything worked as expected. Thanks for your prompt reaction!
