### ISSUE TITLE
With version 7.7 of npp 64bits syntax formatting is neither copied to clipboard nor saved

### ISSUE THREAD

**Issue by FlamMs** [chcg/NPP_ExportPlugin#7]
With last release of Notepad++(7.7 64bits) the formatting stopped to be correctly exported or saved with npp_export plugin.

Please find attached an example of the issue as well as the corresponding generated html code.
[npp_failure_to_export_formatting_2019-06-04 15_01_04.zip](https://github.com/chcg/NPP_ExportPlugin/files/3252492/npp_failure_to_export_formatting_2019-06-04.15_01_04.zip)
![npp_failure_to_export_formatting_2019-06-04 15_01_04](https://user-images.githubusercontent.com/51370112/58881416-75459e00-86da-11e9-93cc-cefd85d74022.jpg)

**Comment by EwingKang** [comment]
I can confirm this with notepad++ with MS Powerpoint.
Just updated today.

**Comment by swampthings** [comment]
I can confirm that it's not working in either the 32 bit or 64 bit version of Notepad++ v. 7.7.

v. 7.6.6 is the last version that this works on. I've reverted back to v. 7.6.6 for my workaround solution.

**Comment by bsacheri** [comment]
I am seeing the same thing.

The right-click context menu "Plugin commands | **Copy Text with Syntax Highlighting**" is no longer copying the formatting. In some cases it is copying the font but never the colors.

I have tested pasting in:
- Outlook
- Word
- OneNote

I have also tested with the options on the **NppExport** plugin menu with the same results.

Here is an image that shows an example:
![Show Example](https://drive.google.com/uc?id=1CIdcDSNgTfnoEJt3bW31HR-ARQjgWH18)

**Comment by chcg** [comment]
See https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.2.9.21

**Comment by ctstacey** [comment]
Hi, good job with this plugin!
From initial testing, it seems like the colours are coming through OK,
however, the colours of comments still seem patchy.
Using the context menu "plugin commands -> copy text with syntax highlighting"

In C or C#, comments made with // and /// come through with colour, but comments made with /* */ come through as black&white.
In Python, comments made with # come though as black&white.
In R, comments made with # come through with colour.
In Haskell, comments made with -- come through with colour.
(I have not tried any other languages)
I hope this would be a simple fix.
If so, I would really appreciate the update.
Many Thanks.

**Comment by pryrt** [comment]
To future readers of this closed issue: in 2024, someone using Notepad++ v8.7 and NppExport v0.4 [reported in the Community Forum](https://community.notepad-plus-plus.org/topic/26213/same-problem-with-npp-8-7-no-colors-copied-with-nppexport-anymore/3) that they were having problems with the color not being included when doing the "copy ___ to clipboard" menu commands from the plugin menu.  

If you are having the same issue, you might want to read that discussion.  But if you don't want to click trough, the short version is:

If you are pasting into Microsoft Office's Word application, by default, it no longer allows pasting color formatting from external applications; if you want to keep all of the formatting that the NppExport puts into the clipboard, instead of pasting with `Ctrl+V`, you need to use Word's **Right Click > Paste Options** menu and select the icon with the paintbrush, which has hover text "`Keep Source Formatting (K)`" 
![](https://community.notepad-plus-plus.org/assets/uploads/files/1729258881542-5a346ef2-e3f0-4ee5-a286-0fc8b033c32c-image.png)
-- this will allow you to paste the fully-formatted text from NppExport into MS Word.  (I believe there's an option in Word's Options to change the default Paste Option for source formatting when pasting from external applications, but you'll have to look through Word's options yourself.)

If you aren't using MS Word, you still might want to see if your destination application has Paste Options or equivalent settings to allow accepting full source formatting.  If you cannot find that option, you might try using the **Export to RTF** or **Export to HTML** to directly create an RTF or HTML file which you should be able to open with your other application.
